# Setup
title:        DaveRGP
tagline:      A responsive theme for your project on GitHub Pages
paginate:     1
baseurl:      ""

# About/contact
author:
  name:       David Parr
  url:        DaveRGP.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
